/** User session metadata */
export default interface ISession {
  /** Datetime when session was created */
  createdAt: string;
  /** Is this user session in command, meaning if it's the one which has access to control elements (only one session per team can) */
  isCommander: boolean;
  /** Team number */
  teamNumber: number;
  /** Team type, supplier or consumer */
  teamType: string;
  /** Session uuid token generated by server */
  token: string;
  /** Datetime when session was updated, for instance to mark it as commander session */
  updatedAt: string;
}
